network_compression_threshold: 256
remote_ping_timeout: 5000
online_mode: false
remote_ping_cache: -1
forge_support: true
max_packets_per_second: 4096
ip_forward: false
disabled_commands:
- disabledcommandhere
max_packets_data_per_second: 33554432
reject_transfers: false
player_limit: -1
connection_throttle: 4000
connection_throttle_limit: 3
prevent_proxy_connections: false
log_commands: false
log_pings: true
stats: 8b7560ce-2930-4681-b0da-da93502649bf
groups:
  md_5:
  - admin
servers:
  lobby:
    motd: Lobby
    address: paper:25565
    restricted: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
listeners:
- query_port: 25577
  motd: '&1Proxy'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 10
  tab_size: 60
  force_default_server: true
enforce_secure_profile: false
server_connect_timeout: 5000
timeout: 30000
